env:
  - GITHUB_TOKEN={{ if index .Env "GITHUB_TOKEN" }}{{ .Env.GITHUB_TOKEN }}{{else}}''{{end}}
archives:
  - format: binary
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary:
      shipyard
    ldflags:
      - -s -w
      - -X shipyard/version.GitCommit={{.Version}}
      - -X shipyard/version.Version={{.ShortCommit}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    tap:
      owner: shipyard
      name: homebrew-tap
      branch: main

    url_template: "https://github.com/shipyardbuild/shipyard-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula

    homepage: "https://shipyard.build/"
    description: "A tool to manage Ephemeral Environments on the Shipyard platform"
    license: "Apache2"

    skip_upload: true
